### PR TITLE
#84 parameterless atom listener

### PR DESCRIPTION
**Pull request by IceTrooper**
This PR is related to #84 Just last commit

### CODE REVIEW

**Comment by soraphis** [comment]
I cherrypicked the one commit for this PR and force pushed it onto the the branch (based on current canary). pls verify that everything is alright. 
thanks

**Comment by AdamRamberg** [comment]
Thanks for the PR! 

Could you do the following changes: 
In `AtomListener.cs` and in the method(s) `OnEventRaised`, please use this syntax `if (_unityEventResponse != null) { _unityEventResponse.Invoke(first, second); }` instead of the null conditional. See https://github.com/dotnet/csharplang/issues/2020
Remove the `[EditorIcon("atom-icon-purple")]` attribute in  `AtomAction`. This was actually never needed in the first place in this file. Needs instead to exist in the final implementation of an AtomAction. 

After the above is fixed I will merge the PR.

**Comment by soraphis** [comment]
> See dotnet/csharplang#2020

UnityEvent inherits from UnityventBase (which inherits from nothing).  it does not inherit from UnityEngine.Object and should not be affected from the null-propagation problematic.

just saying. I actually don't care whether its an if or the propagation syntax.

**Comment by AdamRamberg** [comment]
> UnityEvent inherits from UnityventBase (which inherits from nothing). it does not inherit from UnityEngine.Object and should not be affected from the null-propagation problematic.
> 
> just saying. I actually don't care whether its an if or the propagation syntax.

Aha, that makes sense! Disregard that particular change then :)

**Comment by IceTrooper** [comment]
Done. I thought we need it because you got EditorIcon in every AtomAction\<T\> and etc. Anyway it's done.

**Pull request merged**
