### PR TITLE
add OnCollision hooks

### PR DESCRIPTION
**Pull request by nevernotsean**
This just adds the missing OnCollision MonoHooks. They are the Trigger hooks copied and edited to use the OnCollision mono methods.

This is my first PR for Unity Atoms, so let me know if there is anything else I need to do to get this merged.

### CODE REVIEW

**Comment by AdamRamberg** [comment]
Hi there @nevernotsean! 

Thanks a lot for the PR! 🙏 Sorry for the late reply. 

The OnCollision / OnCollision2D methods are all taking [Collision](https://docs.unity3d.com/ScriptReference/Collision.html) / [Collision2D](https://docs.unity3d.com/ScriptReference/Collision2D.html) parameters, not Collider / Collider2D. In order to get this PR all the way the following things needs to be added: 

1. Generate new atoms for Collision / Collision2D using the generator. These should be added to [`RegenerateAllAtoms.cs`](https://github.com/AdamRamberg/unity-atoms/blob/master/Packages/Core/Editor/Generator/RegenerateAllAtoms.cs). Collider and Collider2D are already defined in `RegenerateAllAtoms.cs` so Collision / Collision2D should follow the same pattern. FYI, There are unfortunately atm some manual work to clean up / re add stuff after a regeneration of everything. 
2. Create 2 new base hooks for Collision / Collision2D called `CollisionHook.cs` / Collision2DHook.cs`. Again, the CollisionHook / Collision2DHook can be used as a template / reference when writing these. 
3. Use the new base hooks in OnCollision2DHook.cs and in OnCollisionHook.cs. 

Let me know if you got any questions!

**Comment by AdamRamberg** [comment]
@nevernotsean I need a couple of more changes in order to merge this: 
- Generate `CollisionGameObject` and `Collision2DGameObject` in `RegenerateAllAtoms.cs` (see how `ColliderGameObject` and `Collider2DGameObject` are defined). Then run the generator to create the new atoms. Otherwise, `Collision2DHook.cs` and `CollisionHook.cs` won't compile. 
-  Implemend `ValueEquals` functions generated removing `throw new NotImplementedException ();`. See how they are implemented for the ”Collider atoms”.

Again, let me know if you got any questions!

**Comment by AdamRamberg** [comment]
Another thing (that might be obvious, but still pointing it out for clarity). First step in my last comment is to create types / classes for `CollisionGameObject.cs` and `Collision2DGameObject.cs`

**Comment by miikalo** [comment]
@nevernotsean Hi, asking because of a long period of inactivity, any updates on this?

**Comment by nevernotsean** [comment]
Hey Miika, no updates. This task was put on the backburner for me. I'll try
to get this back on my todo list soon.

**Comment by Casey-Hofland** [comment]
@nevernotsean any updates on any updates on this? I was wondering if you were going to finish this soon. If not: that's totally ok, please don't feel like you're in my dept (I always do that). But if you don't feel like finishing it anymore, would you please tell me what tasks were left? That way I can fork it myself and add the last missing pieces.

**Comment by nevernotsean** [comment]
Hey Casey, I probably won't have time until next week. Last where I left
off, there were a few recommendations by Adam:

   - Generate CollisionGameObject and Collision2DGameObject in
   RegenerateAllAtoms.cs (see how ColliderGameObject and
   Collider2DGameObject are defined). Then run the generator to create the
   new atoms. Otherwise, Collision2DHook.cs and CollisionHook.cs won't
   compile.
   - Implement ValueEquals functions generated removing throw new
   NotImplementedException ();. See how they are implemented for the
   ”Collider atoms”.

**Comment by AdamRamberg** [comment]
Closing since this exact change was implemented in #221

**Pull request closed without merging**
